import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
   metadataBase: new URL("https://github-explorer-mu-eight.vercel.app"),
  title: "Create Next App",
  description: "Generated by create next app",
   openGraph: {
    title: "GitHub Explorer",
    description:
      "Explore GitHub users, repositories, contributions, and analytics.",
    url: "https://github-explorer-mu-eight.vercel.app",
    siteName: "GitHub Explorer",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
